[phases.setup]
nixPkgs = ['nodejs']

[phases.build]
cmds = [
  'cp -r html/* .',           
  'cp -r css .',              
  'cp -r javascript .',       
  'cp melvo.png .',           
  'cp melvo2.png .'           
]

[start]
cmd = 'npx serve -s .'